[2024-11-28T07:02:51.773+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-28T07:02:51.814+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_green_tripdata.dbt_transform.fct_trips.test scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2024-11-28T07:02:51.839+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_green_tripdata.dbt_transform.fct_trips.test scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2024-11-28T07:02:51.840+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-11-28T07:02:51.877+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): dbt_transform.fct_trips.test> on 2024-11-27 00:00:00+00:00
[2024-11-28T07:02:51.891+0000] {standard_task_runner.py:64} INFO - Started process 1183 to run task
[2024-11-28T07:02:51.897+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'nyc_green_tripdata', 'dbt_transform.fct_trips.test', 'scheduled__2024-11-27T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dag_green_tripdata.py', '--cfg-path', '/tmp/tmpl3lj2fy5']
[2024-11-28T07:02:51.902+0000] {standard_task_runner.py:91} INFO - Job 103: Subtask dbt_transform.fct_trips.test
[2024-11-28T07:02:51.992+0000] {task_command.py:426} INFO - Running <TaskInstance: nyc_green_tripdata.dbt_transform.fct_trips.test scheduled__2024-11-27T00:00:00+00:00 [running]> on host 39c047f38cb8
[2024-11-28T07:02:52.153+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='muhii.smta@gmail.com' AIRFLOW_CTX_DAG_OWNER='Muhii' AIRFLOW_CTX_DAG_ID='nyc_green_tripdata' AIRFLOW_CTX_TASK_ID='dbt_transform.fct_trips.test' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T00:00:00+00:00'
[2024-11-28T07:02:52.156+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-28T07:02:55.578+0000] {local.py:216} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2024-11-28T07:02:55.579+0000] {local.py:432} INFO - Cloning project to writable temp directory /tmp/tmpgvbmyh89 from /opt/airflow/include/dbt
[2024-11-28T07:02:55.591+0000] {local.py:443} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/nyc_green_tripdata__dbt_transform/target/partial_parse.msgpack
[2024-11-28T07:02:55.608+0000] {config.py:332} INFO - Using user-supplied profiles.yml at /opt/airflow/include/dbt/profiles.yml
[2024-11-28T07:02:55.609+0000] {local.py:404} INFO - Trying to run dbtRunner with:
 ['test', '--models', 'fct_trips', '--project-dir', '/tmp/tmpgvbmyh89', '--profiles-dir', '/opt/***/include/dbt', '--profile', 'nyc_taxi', '--target', 'dev']
 in /tmp/tmpgvbmyh89
[2024-11-28T07:02:55.840+0000] {logging_mixin.py:188} INFO - 07:02:55  Running with dbt=1.8.7
[2024-11-28T07:02:57.114+0000] {logging_mixin.py:188} INFO - 07:02:57  Registered adapter: bigquery=1.8.3
[2024-11-28T07:03:02.359+0000] {logging_mixin.py:188} INFO - 07:03:02  Found 7 models, 34 data tests, 2 sources, 600 macros
[2024-11-28T07:03:02.368+0000] {logging_mixin.py:188} INFO - 07:03:02
[2024-11-28T07:03:03.254+0000] {logging_mixin.py:188} INFO - 07:03:03  Concurrency: 1 threads (target='dev')
[2024-11-28T07:03:03.259+0000] {logging_mixin.py:188} INFO - 07:03:03
[2024-11-28T07:03:03.271+0000] {logging_mixin.py:188} INFO - 07:03:03  1 of 12 START test not_null_fct_trips_do_location_id ........................... [RUN]
[2024-11-28T07:03:05.904+0000] {logging_mixin.py:188} INFO - 07:03:05  1 of 12 PASS not_null_fct_trips_do_location_id ................................. [PASS in 2.63s]
[2024-11-28T07:03:05.913+0000] {logging_mixin.py:188} INFO - 07:03:05  2 of 12 START test not_null_fct_trips_dropoff_time_id .......................... [RUN]
[2024-11-28T07:03:08.182+0000] {logging_mixin.py:188} INFO - 07:03:08  2 of 12 PASS not_null_fct_trips_dropoff_time_id ................................ [PASS in 2.27s]
[2024-11-28T07:03:08.189+0000] {logging_mixin.py:188} INFO - 07:03:08  3 of 12 START test not_null_fct_trips_extra .................................... [RUN]
[2024-11-28T07:03:10.241+0000] {logging_mixin.py:188} INFO - 07:03:10  3 of 12 PASS not_null_fct_trips_extra .......................................... [PASS in 2.05s]
[2024-11-28T07:03:10.249+0000] {logging_mixin.py:188} INFO - 07:03:10  4 of 12 START test not_null_fct_trips_improvement_surcharge .................... [RUN]
[2024-11-28T07:03:12.301+0000] {logging_mixin.py:188} INFO - 07:03:12  4 of 12 PASS not_null_fct_trips_improvement_surcharge .......................... [PASS in 2.05s]
[2024-11-28T07:03:12.312+0000] {logging_mixin.py:188} INFO - 07:03:12  5 of 12 START test not_null_fct_trips_passenger_count .......................... [RUN]
[2024-11-28T07:03:14.267+0000] {logging_mixin.py:188} INFO - 07:03:14  5 of 12 PASS not_null_fct_trips_passenger_count ................................ [PASS in 1.95s]
[2024-11-28T07:03:14.274+0000] {logging_mixin.py:188} INFO - 07:03:14  6 of 12 START test not_null_fct_trips_payment_type ............................. [RUN]
[2024-11-28T07:03:16.259+0000] {logging_mixin.py:188} INFO - 07:03:16  6 of 12 PASS not_null_fct_trips_payment_type ................................... [PASS in 1.98s]
[2024-11-28T07:03:16.267+0000] {logging_mixin.py:188} INFO - 07:03:16  7 of 12 START test not_null_fct_trips_pickup_time_id ........................... [RUN]
[2024-11-28T07:03:18.238+0000] {logging_mixin.py:188} INFO - 07:03:18  7 of 12 PASS not_null_fct_trips_pickup_time_id ................................. [PASS in 1.97s]
[2024-11-28T07:03:18.247+0000] {logging_mixin.py:188} INFO - 07:03:18  8 of 12 START test not_null_fct_trips_pu_location_id ........................... [RUN]
[2024-11-28T07:03:20.131+0000] {logging_mixin.py:188} INFO - 07:03:20  8 of 12 PASS not_null_fct_trips_pu_location_id ................................. [PASS in 1.88s]
[2024-11-28T07:03:20.147+0000] {logging_mixin.py:188} INFO - 07:03:20  9 of 12 START test not_null_fct_trips_rate_code_id ............................. [RUN]
[2024-11-28T07:03:23.569+0000] {logging_mixin.py:188} INFO - 07:03:23  9 of 12 PASS not_null_fct_trips_rate_code_id ................................... [PASS in 3.42s]
[2024-11-28T07:03:23.581+0000] {logging_mixin.py:188} INFO - 07:03:23  10 of 12 START test not_null_fct_trips_trip_distance ........................... [RUN]
[2024-11-28T07:03:25.705+0000] {logging_mixin.py:188} INFO - 07:03:25  10 of 12 PASS not_null_fct_trips_trip_distance ................................. [PASS in 2.12s]
[2024-11-28T07:03:25.722+0000] {logging_mixin.py:188} INFO - 07:03:25  11 of 12 START test not_null_fct_trips_vendor_id ............................... [RUN]
[2024-11-28T07:03:27.812+0000] {logging_mixin.py:188} INFO - 07:03:27  11 of 12 PASS not_null_fct_trips_vendor_id ..................................... [PASS in 2.09s]
[2024-11-28T07:03:27.820+0000] {logging_mixin.py:188} INFO - 07:03:27  12 of 12 START test unique_fct_trips_trip_id ................................... [RUN]
[2024-11-28T07:03:29.851+0000] {logging_mixin.py:188} INFO - 07:03:29  12 of 12 FAIL 59326 unique_fct_trips_trip_id ................................... [FAIL 59326 in 2.03s]
[2024-11-28T07:03:29.863+0000] {logging_mixin.py:188} INFO - 07:03:29
[2024-11-28T07:03:29.866+0000] {logging_mixin.py:188} INFO - 07:03:29  Finished running 12 data tests in 0 hours 0 minutes and 27.49 seconds (27.49s).
[2024-11-28T07:03:30.029+0000] {logging_mixin.py:188} INFO - 07:03:30
[2024-11-28T07:03:30.033+0000] {logging_mixin.py:188} INFO - 07:03:30  Completed with 1 error and 0 warnings:
[2024-11-28T07:03:30.036+0000] {logging_mixin.py:188} INFO - 07:03:30
[2024-11-28T07:03:30.039+0000] {logging_mixin.py:188} INFO - 07:03:30  Failure in test unique_fct_trips_trip_id (models/tests/schema.yml)
[2024-11-28T07:03:30.042+0000] {logging_mixin.py:188} INFO - 07:03:30    Got 59326 results, configured to fail if != 0
[2024-11-28T07:03:30.045+0000] {logging_mixin.py:188} INFO - 07:03:30
[2024-11-28T07:03:30.048+0000] {logging_mixin.py:188} INFO - 07:03:30    compiled code at target/compiled/nyc_taxi/models/tests/schema.yml/unique_fct_trips_trip_id.sql
[2024-11-28T07:03:30.051+0000] {logging_mixin.py:188} INFO - 07:03:30
[2024-11-28T07:03:30.055+0000] {logging_mixin.py:188} INFO - 07:03:30  Done. PASS=11 WARN=0 ERROR=1 SKIP=0 TOTAL=12
[2024-11-28T07:03:31.432+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-11-28T07:03:31.434+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-11-28T07:03:31.448+0000] {local.py:490} INFO - Inlets: [Dataset(uri='bigquery/northern-shield-437204-m0.nyc_taxi.fct_trips', extra=None)]
[2024-11-28T07:03:31.449+0000] {local.py:491} INFO - Outlets: []
[2024-11-28T07:03:31.450+0000] {local.py:590} INFO - Assigning inlets/outlets without DatasetAlias
[2024-11-28T07:03:31.451+0000] {dag.py:3089} INFO - Sync 1 DAGs
[2024-11-28T07:03:31.494+0000] {dag.py:3947} INFO - Setting next_dagrun for nyc_green_tripdata to None, run_after=None
[2024-11-28T07:03:31.554+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-28T07:03:31.576+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/cosmos/operators/local.py", line 763, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.9/site-packages/cosmos/operators/local.py", line 649, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/cosmos/operators/local.py", line 502, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.9/site-packages/cosmos/operators/local.py", line 233, in handle_exception_dbt_runner
    raise AirflowException(f"dbt invocation completed with errors: {error_message}")
airflow.exceptions.AirflowException: dbt invocation completed with errors: unique_fct_trips_trip_id: Got 59326 results, configured to fail if != 0
[2024-11-28T07:03:31.583+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=nyc_green_tripdata, task_id=dbt_transform.fct_trips.test, run_id=scheduled__2024-11-27T00:00:00+00:00, execution_date=20241127T000000, start_date=20241128T070251, end_date=20241128T070331
[2024-11-28T07:03:31.610+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 103 for task dbt_transform.fct_trips.test (dbt invocation completed with errors: unique_fct_trips_trip_id: Got 59326 results, configured to fail if != 0; 1183)
[2024-11-28T07:03:31.717+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-28T07:03:31.733+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
